name:  Ansible  Lint

on:
    pull_request:
      paths:
           - "playbooks/**"
           - "roles/**"
           - "inventories/**"

jobs:
   lint:
       runs-on:  ubuntu-latest
      steps:
           - uses:  actions/checkout@v4
          -  name:  Install  Ansible &  ansible-lint
              run:  |
                 pip  install ansible  ansible-lint
          -  name:  Run  ansible-lint
             run:  ansible-lint  playbooks/*.yml
